djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
]

mysite/urls.py
from django.urls import path

from mysite.views import index, new_person, select, triangle, update_person


app_name = "mysite"
urlpatterns = [
    path('triangle/', triangle, name="triangle"),
    path('person/', new_person, name="new_person"),
    path('index/', index, name="index"),
    path('person/<int:pk>/', update_person, name="update_person"),
    path('person/select/', select, name='select')
]

catalog/models.py
from django.db import models


class City(models.Model):
    city = models.CharField(max_length=50)

    def __str__(self):
        return self.city


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Client(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    product = models.ManyToManyField(Product)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    city = models.OneToOneField(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

mysite/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Log(models.Model):
    path = models.CharField(max_length=300)
    method = models.CharField(max_length=300)
    timestamp = models.DateField(auto_now_add=True)

mysite/forms.py
from django import forms

from mysite.models import Person


class GetForm(forms.Form):
    first_cathetus = forms.IntegerField(label='first value', required=True, min_value=1)
    second_cathetus = forms.IntegerField(label='second value', required=True, min_value=1)


class PersonModelForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

mysite/views.py
from django.shortcuts import get_object_or_404, redirect, render

from mysite.forms import GetForm, PersonModelForm
from mysite.models import Person


def index(request):
    return render(request, 'mysite/index.html')


def select(request):
    objects = Person.objects.all()
    return render(request, 'mysite/select.html', {'objects': objects, })


def triangle(request):
    hypotenuse = None
    if 'submit' in request.GET:
        _get_form = GetForm(request.GET)
        if _get_form.is_valid():
            first = _get_form.cleaned_data['first_cathetus']
            second = _get_form.cleaned_data['second_cathetus']
            third = first ** 2 + second ** 2
            hypotenuse = round(third ** 0.5)
    else:
        _get_form = GetForm()
    return render(request, 'mysite/answer_mysite.html', {'get_form': _get_form, "hypotenuse": hypotenuse})


def new_person(request):
    if request.method == 'POST':
        person_form = PersonModelForm(data=request.POST)
        if person_form.is_valid():
            person_form.save()
            return redirect('mysite:index')
    else:
        person_form = PersonModelForm()
    return render(
        request,
        'mysite/person_form.html',
        {
            'person_form': person_form,
        }
    )


def update_person(request, pk):
    user = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        person_form = PersonModelForm(data=request.POST, instance=user)
        if person_form.is_valid():
            person_form.save()
            return redirect('mysite:index')
    else:
        person_form = PersonModelForm(instance=user)
    return render(
        request,
        'mysite/update_person.html',
        {
            'person_form': person_form,
            'user': user,
        }
    )

templates/mysite/answer_mysite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Formula</h1>
{% if hypotenuse %}
    <h2>Hypotenuse = {{ hypotenuse }}</h2>
{% endif %}
<form action="{% url 'mysite:triangle' %}" method="get">
    {{ get_form.as_p }}
    <input type="submit" name="submit" value="OK">
</form>
</body>
</html>

templates/mysite/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p><a href="{% url 'mysite:triangle' %}">Formula triangle</a></p>
    <p><a href="{% url 'mysite:new_person' %}">Create new person</a></p>
    <p><a href="{% url 'mysite:select' %}">Select to change</a></p>

</body>
</html>

templates/mysite/person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My site</title>
</head>
<body>
<h1>New person</h1>
<form action="{% url 'mysite:new_person' %}" method="post">
    {% csrf_token %}
    {{ person_form.as_p }}
    <input type="submit" value="SAVE">
</form>
</body>
</html>

templates/mysite/select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My site</title>
</head>
<body>
<h1>Select to change</h1>
    <ul>
        {% for obj in objects %}
            <li><a href="{% url 'mysite:update_person' pk=obj.pk %}">{{ obj }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/mysite/update_person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My site</title>
</head>
<body>
<h1>Update person</h1>
<form action="{% url 'mysite:update_person' pk=user.pk %}" method="post">
    {% csrf_token %}
    {{ person_form.as_p }}
    <input type="submit" value="UPDATE">
</form>
</body>
</html>